# Generated by Django 5.2.17 on 2026-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tech_stack', models.CharField(blank=True, help_text='Через запятую: Python, Django, PostgreSQL', max_length=300, verbose_name='Технологии')),
                ('url', models.URLField(blank=True, verbose_name='Демо/сайт')),
                ('repo_url', models.URLField(blank=True, verbose_name='Репозиторий')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Скриншот')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
