# Generated by Django 5.2.17 on 2026-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('tagline', models.CharField(help_text='Например: Backend-разработчик и автор технического блога', max_length=200, verbose_name='Кто вы (одной строкой)')),
                ('about', models.TextField(verbose_name='Обо мне')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фото')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
