# Generated by Django 5.2.17 on 2026-09-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('excerpt', models.CharField(blank=True, help_text='Показывается в списке постов и в мета-описании', max_length=300, verbose_name='Краткое описание')),
                ('content', models.TextField(help_text='Поддерживается Markdown-подобная разметка или чистый HTML', verbose_name='Текст')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Обложка')),
                ('tags', models.CharField(blank=True, help_text='Через запятую: Python, Django, DevOps', max_length=200, verbose_name='Теги')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
    ]
