# Generated by Django 5.2.17 on 2026-10-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event', models.CharField(blank=True, help_text='Например: Heisenbug, SQADays, митап в офисе', max_length=200, verbose_name='Мероприятие')),
                ('video', models.FileField(blank=True, help_text='MP4 или WebM играются в браузере напрямую; MOV/AVI лучше конвертировать в MP4', null=True, upload_to='talks/', verbose_name='Видеофайл')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/VK/ Rutube — если видео хостится снаружи', verbose_name='Ссылка на видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='talks/thumbs/', verbose_name='Превью')),
                ('spoke_at', models.DateField(blank=True, null=True, verbose_name='Дата выступления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Выступление',
                'verbose_name_plural': 'Выступления',
                'ordering': ['-spoke_at', '-created_at'],
            },
        ),
    ]
